#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{branch}-{build}'

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
    files:
        - docs/*

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
- Visual Studio 2015
- Visual Studio 2017

# set clone depth
clone_depth: 1

# clone directory
clone_folder: c:\projects\render_pipeline_cpp

# scripts that are called at very beginning, before repo cloning
init:
- ps: >-
    if (Test-Path env:TRIGGER_NAME) {
        Update-AppveyorBuild -Message "Build by $env:TRIGGER_BUILD_VERSION in $env:TRIGGER_NAME"
    }
- git --version
- python --version
- cmake --version
- ps: >-
    if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2015") {
        $env:CMAKE_GENERATOR="Visual Studio 14 2015 Win64"
    } else {
        $env:CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
    }

# environment variables
environment:
    CMAKE_PREFIX_PATH: C:\projects\_install;
    BOOST_ROOT: C:\Libraries\boost_1_65_1
    PATH: C:\Python36-x64;%PATH%
    FREETYPE_DIR: C:\projects\_install\panda3d-thirdparty\win-libs-vc14-x64\freetype

# this is how to allow failing jobs in the matrix
matrix:
    fast_finish: true   # set this flag to immediately finish build once one of the jobs fails.
    exclude:
        - configuration: Debug
          image: Visual Studio 2015
        - configuration: RelWithDebInfo
          image: Visual Studio 2015

# scripts that run after cloning repository
install:
- ps: (mkdir C:\projects\_install) -and (pushd C:\projects\_install)
- ps: >-
    if ($env:CONFIGURATION -eq "Debug") {
        Start-FileDownload 'https://ci.appveyor.com/api/projects/bluekyu/panda3d-thirdparty/artifacts/panda3d-thirdparty.7z?branch=master&job=Configuration%3A+MixForDebug'
    } else {
        Start-FileDownload 'https://ci.appveyor.com/api/projects/bluekyu/panda3d-thirdparty/artifacts/panda3d-thirdparty.7z?branch=master&job=Configuration%3A+Release'
    }
- 7z x -y panda3d-thirdparty.7z > nul
- ps: >-
    if ($env:CONFIGURATION -eq "Debug") {
        Start-FileDownload 'https://ci.appveyor.com/api/projects/bluekyu/panda3d/artifacts/panda3d.7z?branch=master&job=Configuration%3A+Debug'
    } else {
        Start-FileDownload 'https://ci.appveyor.com/api/projects/bluekyu/panda3d/artifacts/panda3d.7z?branch=master&job=Configuration%3A+Release'
    }
- 7z x -y panda3d.7z > nul
- ps: Start-FileDownload ('https://ci.appveyor.com/api/projects/bluekyu/cpp-packages/artifacts/install/spdlog.7z?branch=master&job=Configuration%3A+' + "$env:CONFIGURATION")
- 7z x -y spdlog.7z > nul
- ps: Start-FileDownload ('https://ci.appveyor.com/api/projects/bluekyu/cpp-packages/artifacts/install/yaml-cpp.7z?branch=master&job=Configuration%3A+' + "$env:CONFIGURATION")
- 7z x -y yaml-cpp.7z > nul
- ps: popd

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
- Debug
- RelWithDebInfo
- Release

build:
    parallel: true                  # enable MSBuild parallel builds

# to run your custom scripts instead of automatic MSBuild
build_script:
- ps: (mkdir _build) -and (pushd _build)
- cmd: >-
    cmake -G "%CMAKE_GENERATOR%" -Wno-dev ..
    -DCMAKE_INSTALL_PREFIX="C:/projects/_install/render_pipeline_cpp"
    -Dpanda3d_ROOT:PATH="C:/projects/_install/panda3d"
- cmake --build . --config %CONFIGURATION% --target install
- ps: popd

after_build:
- 7z a render_pipeline_cpp.7z "C:/projects/_install/render_pipeline_cpp"

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: render_pipeline_cpp.7z

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:
- ps: >-
    if (($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017") -and ($env:CONFIGURATION -eq "Release") -and ($env:APPVEYOR_REPO_BRANCH -eq "master")) {
        Start-AppveyorBuild -ApiKey $env:api_key -ProjectSlug 'rpcpp-plugins' -EnvironmentVariables @{
            TRIGGER_NAME = $env:APPVEYOR_PROJECT_NAME
            TRIGGER_BUILD_VERSION = $env:APPVEYOR_BUILD_VERSION
        }
    }
